name: ${project.name}
main: be.bendem.bukkit.orebroadcast.OreBroadcast
version: ${project.version}
author: bendem
authors: [graywolf336, EpiCanard]
description: Send messages to other players when you find ores.
api-version: 1.13

commands:
    ob:
        usage: |
            OreBroadcast command. Type '/ob help' for more informations
        description: OreBroadcast commands
        permission: ob.commands.reload

permissions:
    ob.*:
        description: Give access to all OreBroadcast functionalities
        children:
            ob.broadcast: true
            ob.receive: true
            ob.commands.reload: true
    ob.commands.reload:
        description: Players with this permission can reload the config
        default: op
    ob.broadcast:
        description: Players with this permission will send messages when they find ores.
        default: true
    ob.receive:
        description: Players with this permission will receive OreBroadcast messages.
        default: op
